
# .streamlit/secrets.toml

[gsheet]
entradas = "https://docs.google.com/spreadsheets/d/1MOBhw3k85Ps7uFbH_kzG8Gkd-z9w4UQRX97YuqEPuNE/export?format=csv"
necessidades = "https://docs.google.com/spreadsheets/d/1HrniJ7LgrV6oinc1XnwamtLwPLG9DZ5vtzuuMJ2fdNc/export?format=csv"



